-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: May 12, 2016 at 07:52 PM
-- Server version: 5.6.21
-- PHP Version: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `test`
--

-- --------------------------------------------------------

--
-- Table structure for table `web_information`
--

CREATE TABLE IF NOT EXISTS `web_information` (
`id` int(11) NOT NULL,
  `meta_title` varchar(100) NOT NULL,
  `meta_description` varchar(300) NOT NULL,
  `site_url` varchar(300) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=199 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `web_information`
--

INSERT INTO `web_information` (`id`, `meta_title`, `meta_description`, `site_url`) VALUES
(1, 'Bulk Product Data Insert,Update CSV File into Database Using PHP and Mysqli', 'In this post we will discuses about how to insert and update bulk CSV file data into the database. php script to import csv file into mysql database,import csv file into mysql using php demo,how to read csv file in php and store in mysql,import data from excel to mysql using php code,php import csv ', 'http://www.mostlikers.com/2016/04/bulk-product-data-insertupdate-csv-file.html'),
(2, 'Codeigniter SEO Friendly URL Structure', 'Codeigniter SEO Friendly URL Structure codeigniter seo friendly url htaccess,codeigniter seo plugin,codeigniter seo library\ncodeigniter url routing,how to remove index.php from url in codeigniter,codeigniter htaccess file\ncodeigniter url segment,codeigniter 3 htaccess,codeigniter seo tips,codeignite', 'http://www.mostlikers.com/2016/04/codeigniter-seo-friendly-url-structure.html'),
(3, 'Providing Security to the website forms', 'Most of the website forms face security issues.how to provide security to website in php,providing security to restful web services\nproviding security in 4g systems unveiling the challenges,secure website forms\nhow to create a secure web form,creating a secure website,how to create a secure website ', 'http://www.mostlikers.com/2016/03/providing-security-to-website-forms.html'),
(4, 'Read Your Gmails Using PHP and IMAP', 'Int this post i will explain about how to access gmail inbox  mail via php code. Here i am using PHP 5 IMAP  function to retrieve gmail inbox emails. IMAP function used to open streams to POP3 and NNTP servers.php imap_open\nphp imap gmail', 'http://www.mostlikers.com/2016/01/read-your-gmails-using-php-and-imap.html'),
(5, 'Git Tutorial - Git Configurations #1', 'git tutorial There are three levels that the Git stores the configurations.System Level Configurations, User Level Configurations and Project Level Configurations.git tutorial for beginners,git tutorial pdf,github tutorial,git commands\ngit cheat sheet,git tutorial video,git push ,git tutorial window', 'http://www.mostlikers.com/2016/01/git-tutorial-git-configurations-1.html'),
(6, 'Git Tutorial - Installation', 'It is a software that keeps a track of files and directories that we make; especially the text changes and allows us to compare between the versions that we created. GIT is referred as a version control system (VCS). The primary purpose of the VCS is to manage the source code, i.e., the source code ', 'http://www.mostlikers.com/2016/01/git-tutorial-installation.html'),
(7, 'Git Tutorial - Introduction', 'It is a software that keeps a track of files and directories that we make; especially the text changes and allows us to compare between the versions that we created. GIT is referred as a version control system (VCS). The primary purpose of the VCS is to manage the source code, i.e., the source code ', 'http://www.mostlikers.com/2016/01/git-tutorial-introduction.html'),
(8, 'HTML4 vs HTML5 Page Structure', 'This post is about the differences between HTML4 and HTML5, the difference between the HTML elements, tags, page structure, browser support and which one to choose. This post is a lengthier one so it will be divided into two parts. All the website follow a common structure of header, navigation, sid', 'http://www.mostlikers.com/2016/01/html4-vs-html5-page-structure_12.html'),
(9, 'Bootstrap Tutorial - My First Code', 'Bootstrap uses the HTML elements for creating the layouts and CSS for styling the layout, that means you will not have to learn any other coding language just the HTML, CSS and JavaScript which are the website languages.', 'http://www.mostlikers.com/2015/12/bootstrap-tutorial-my-first-code.html'),
(10, 'Bootstrap Tutorial - Introduction', 'Bootstrap was developed by Mark Otto and Jacob Thornton on August 2011. Bootstrap is a front end framework built using HTML, CSS and JavaScript, for building for responsive web sites. It is faster and easier to use and sometimes a little tricky. It is called as a mobile first framework. It is an ope', 'http://www.mostlikers.com/2015/12/bootstrap-tutorial-introduction.html'),
(11, 'Fetch Random rows records from Database Using Mysqli and PHP', 'In this tutorial you will learn various techniques to how to Fetch Random rows records from Database. Using this code you can display random gallery profile, Online examination random questions, multiple choice quiz system. I used following simple query for retrieving random records from database ta', 'http://www.mostlikers.com/2015/12/fetch-random-rows-records-from-database.html'),
(12, 'Simple Subscribe and Unsubscribe Script in PHP', 'A newsletter is a regularly distributed publication via email in register subscribe user. In this post i have explain about How to create simple news letter subscription script in php. Here i have created very simple code to Subscribe and Unsubscribe email user list.', 'http://www.mostlikers.com/2015/11/simple-subscribe-and-unsubscribe-script.html'),
(13, 'Text fade in fade out effect using jquery', 'Text fade in fade out effect using jquery, fadeIn   - This method used to hidden the element. fadeIn callback parameter is a function to be executed after the fading completes.\n\nfadeOut() - This method used to visible the hidden element. It can take the slow and fast effect based on milliseconds. \n\n', 'http://www.mostlikers.com/2015/11/text-fade-in-fade-out-effect-using.html'),
(14, 'Facebook like fetch YouTube embed videos from url using PHP and Ajax', 'Have you shared YouTube video url in facebook timeline.  while typing the link YouTube video will preview the timeline. I had developed Facebook like fetch YouTube embed videos from url using PHP and Ajax with live demo.', 'http://www.mostlikers.com/2015/11/facebook-like-fetch-youtube-embed.html'),
(15, 'New User Registration With Email Verification Using PHP and Mysqli', 'In this post i have explain about how to implement New user registration with email verification script. if your using register form in a website, you need to use email verification because it will be reduce spam register user and make sure you will get correct registered user in your website.', 'http://www.mostlikers.com/2015/11/new-user-registration-with-email-verifcation.html'),
(16, 'Get all child, grandchild etc nodes under parent array using php with mysqli', 'In this post i have explain about how to implement New user registration with email verification script. if your using register form in a website, you need to use email verification because it will be reduce spam register user and make sure you will get correct registered user in your website.', 'http://www.mostlikers.com/2015/10/get-all-child-grandchild-etc-nodes.html'),
(17, 'Youtube video embed code tricks', 'How to Remove YouTube Logo & Branding from Embedded code,codeigniter youtube channel embed,Disable Related Videos,Autoplay and loop youtube video,Remove YouTube Player Controls and Title,Remove YouTube annotations', 'http://www.mostlikers.com/2015/10/youtube-video-embed-code-tricks.html'),
(18, 'Remove row from table with fadeOut effect using jquery and php', 'delete data from database fadeout In this post i have explain about Remove row from table with fadeOut effect using jquery and php. Here i have used ajax to delete the database record. It will work without refresh page and row table data delete with fadeOut effect. jquery delete table row animation\n', 'http://www.mostlikers.com/2015/09/remove-row-from-table-with-fadeout.html'),
(19, ' Image Mouse Over Effect using CSS3 and jQuery', 'image hover effect jquery free download,mouse over effect in css,image hover effect css3,jquery image hover effect using one image,jquery image hover effect with caption,jquery hover effects on div,jquery text hover effects,jquery image hover zoom,', 'http://www.mostlikers.com/2015/09/image-mouse-over-effect-using-css3-and.html'),
(20, 'CSS3 image zoom fade effect', 'image hover effect jquery free download,mouse over effect in css,image hover effect css3,jquery image hover effect using one image,jquery image hover effect with caption,jquery hover effects on div,jquery text hover effects,jquery image hover zoom,', 'http://www.mostlikers.com/2015/08/css3-image-zoom-fade-effect.html'),
(21, 'Product search filtering using php and ajax', 'In this post i have created product filters in a webpage like that of Flipkart and Amazon. Here i have used ajax function, It will get result without refresh page. Follow this simple code create ecommerce site search filter. Search filter like amazon filpkart, ecommerce site search filter in php, se', 'http://www.mostlikers.com/2015/08/product-search-filtering-using-php-and.html'),
(22, 'Convert PHP data to JSON API url', 'Convert PHP data to JSON API url. Today i have discussed about Convert php result array to json api url. JSON is a light-weight data-interchange format. Current trend to develop the api and web app server side exchanging data between their servers  XML or JSON format. JSON is the easiest way to tran', 'http://www.mostlikers.com/2015/08/convert-php-data-to-json-api-url.html'),
(23, 'Forget password recovery using Ajax, php and mysqli', 'In this tutorial i want to discuses about Forget password recovery using php and mysqli.forgot password code in php example\nforgot password code in php free download\nforgot password code in php mysql\nforgot password code in php with demo', 'http://www.mostlikers.com/2015/07/forget-password-recovery-using-ajax-php.html'),
(24, 'Make seo trick for title tag using javascript', 'Make seo trick for title tag using javascript,Make your html title tag website traffic .Title tags are part of the meta tags that appear at the top of your HTML inside the < head> area. it will display on browser tab title.Blink Effect in title tag script,Marquee Effect in title tag script', 'http://www.mostlikers.com/2015/06/make-seo-trick-for-title-tag-using.html'),
(25, 'CSS3 image rotate animation effect', 'CSS3 image rotate animation effect,', 'http://www.mostlikers.com/2015/06/css3-image-rotate-animation-effect.html'),
(26, 'Display Flash Message in CodeIgniter', 'Display Flash Message in CodeIgniter,How to Display Error Message in CodeIgniter,Set flash data in controller', 'http://www.mostlikers.com/2015/06/display-flash-message-in-codeigniter.html'),
(27, 'Generate RSS Feed for website using php and json script', 'Generate RSS Feed for website using php and json script,Generate RSS Feed with PHP, rss feed in blog', 'http://www.mostlikers.com/2015/06/generate-rss-feed-for-website-using-php.html'),
(28, 'CodeIgniter Remove index.php in URL', 'In this post i want to discuses about how to remove CodeIgniter  index.php in URL. Previously i have posted CodeIgniter related topics. While i am creating new CodeIgniter project i have to set config file url configuration index.php and i feel my url path also not looking good. i have used below ht', 'http://www.mostlikers.com/2015/05/codeigniter-remove-indexphp-in-url.html'),
(29, 'Login with facebook using codeigniter', 'facebook login codeigniter tutorial,codeigniter facebook auth,codeigniter facebook login example,codeigniter facebook login tutorial,codeigniter facebook login integration,facebook connect php example,codeigniter facebook login library,codeigniter login system,codeigniter login script,codeigniter lo', 'http://www.mostlikers.com/2015/04/login-with-facebook-using-codeigniter.html'),
(30, 'Jquery image on click effects', 'facebook login codeigniter tutorial,codeigniter facebook auth,codeigniter facebook login example,codeigniter facebook login tutorial,codeigniter facebook login integration,facebook connect php example,codeigniter facebook login library,codeigniter login system,codeigniter login script,codeigniter lo', 'http://www.mostlikers.com/2015/04/jquery-image-on-click-effects.html'),
(31, 'CodeIgniter My Model', 'facebook login codeigniter tutorial,codeigniter facebook auth,codeigniter facebook login example,codeigniter facebook login tutorial,codeigniter facebook login integration,facebook connect php example,codeigniter facebook login library,codeigniter login system,codeigniter login script,codeigniter lo', 'http://www.mostlikers.com/2015/04/codeigniter-my-model.html'),
(32, 'Codeigniter load CSS and Javascript files', 'facebook login codeigniter tutorial,codeigniter facebook auth,codeigniter facebook login example,codeigniter facebook login tutorial,codeigniter facebook login integration,facebook connect php example,codeigniter facebook login library,codeigniter login system,codeigniter login script,codeigniter lo', 'http://www.mostlikers.com/2015/04/in-this-post-i-have-explan-about-how-we.html'),
(33, 'Analyze and optimize your website with google PageSpeed tools', 'facebook login codeigniter tutorial,codeigniter facebook auth,codeigniter facebook login example,codeigniter facebook login tutorial,codeigniter facebook login integration,facebook connect php example,codeigniter facebook login library,codeigniter login system,codeigniter login script,codeigniter lo', 'http://www.mostlikers.com/2015/03/analyze-and-optimize-your-website-with.html'),
(34, 'Convert html to codeigniter and basic steps of codeigniter', 'facebook login codeigniter tutorial,codeigniter facebook auth,codeigniter facebook login example,codeigniter facebook login tutorial,codeigniter facebook login integration,facebook connect php example,codeigniter facebook login library,codeigniter login system,codeigniter login script,codeigniter lo', 'http://www.mostlikers.com/2015/03/convert-html-to-codeigniter-and-basic.html'),
(35, 'PDO basic insert,view,update,delete with php function', 'PDO basic insert,view,update,delete with php function. The mysql extension is deprecated and will be removed in the future use mysqli or PDO. mysqli based on object oriented better i would have suggested PDO. The PHP Data Objects (PDO) extension defines a lightweight, consistent interface for access', 'http://www.mostlikers.com/2015/03/pdo-basic-insertviewupdatedelete-with.html'),
(36, 'Ajax add,view and delete using mysqli', 'insert delete update data using ajax in php,insert update delete in php with source code\ninsert update delete in php in one form,insert update delete in php in one page\nmysqli update query example,insert update delete in php using oops,insert update delete in php on same page\nphp insert update delet', 'http://www.mostlikers.com/2015/03/ajax-addview-and-delete-using-mysqli.html'),
(37, 'Sql Basic functions', 'insert delete update data using ajax in php,insert update delete in php with source code\ninsert update delete in php in one form,insert update delete in php in one page\nmysqli update query example,insert update delete in php using oops,insert update delete in php on same page\nphp insert update delet', 'http://www.mostlikers.com/2015/02/sql-basic-functions.html'),
(38, 'Send email with html template using  php', 'Today i want explain about send email with html template using php\nphp mail html template,email html template generator,email html template code\nsimple email html template\nemail html template design\nemail html template free\nemail html template example\nemail html template tutorial', 'http://www.mostlikers.com/2015/02/send-email-with-html-template-using-php.html'),
(39, 'Active and inactive users concept using php and Ajax', 'Today i want explain about send email with html template using php\nphp mail html template,email html template generator,email html template code\nsimple email html template\nemail html template design\nemail html template free\nemail html template example\nemail html template tutorial', 'http://www.mostlikers.com/2015/02/active-and-inactive-users-concept-using.html'),
(40, 'Auto suggest username like gmail using php with ajax', 'Today i want explain about send email with html template using php\nphp mail html template,email html template generator,email html template code\nsimple email html template\nemail html template design\nemail html template free\nemail html template example\nemail html template tutorial', 'http://www.mostlikers.com/2015/02/auto-suggest-username-like-gmail-using.html'),
(41, 'Google style app container drop down using bootstrap with jquery', 'Today i want explain about send email with html template using php\nphp mail html template,email html template generator,email html template code\nsimple email html template\nemail html template design\nemail html template free\nemail html template example\nemail html template tutorial', 'http://www.mostlikers.com/2015/02/google-style-app-container-drop-down.html'),
(42, 'Share your website link to social media website (New)', 'Today i want explain about send email with html template using php\nphp mail html template,email html template generator,email html template code\nsimple email html template\nemail html template design\nemail html template free\nemail html template example\nemail html template tutorial', 'http://www.mostlikers.com/2015/01/share-your-website-link-to-social-media.html'),
(43, 'Ajax PHP Login Page with bootstrap design', 'Ajax PHP Login Page with boostrap design concept. Simple Ajax Login form with jQuery and PHP, How make a login system using ajax without refreshing', 'http://www.mostlikers.com/2015/01/ajax-php-login-page-with-boostrap-design.html'),
(44, 'Php contact form captcha code using Ajax', 'what is use of captcha, How to Create CAPTCHA Protection using PHP and AJAX,PHP Built-In Ajax CAPTCHA Validation Code Sample,Today i am going explain about Php contact form captcha code using Ajax concept. Why we use to captch in website, This protects your website for spammers and robots. Here i wa', 'http://www.mostlikers.com/2015/01/php-contact-form-captcha-code-using-ajax.html'),
(45, 'Export html table data to csv file using JavaScript', 'Export html table data to csv file using JavaScript,Recently i have posted Import CSV File Data Into Database Using PHP article this concept based import excel sheet data into database.Similar like i have posted this topic, here i am using JavaScript for converting html table data into excel (CSV) d', 'http://www.mostlikers.com/2015/01/export-html-table-data-to-csv-file.html'),
(46, 'Dynamically adding HTML form field using jQuery', 'Dynamically adding HTML form field using jQuery, Div generator jquery', 'http://www.mostlikers.com/2015/01/dynamically-adding-html-form-field.html'),
(47, 'Show loading image while Page is loading using jQuery', 'Show loading image while Page is loading using jQuery, page loader script', 'http://www.mostlikers.com/2014/12/show-loading-image-while-page-is.html'),
(48, 'Expiry date code in php', '$startTime = strtotime($puechese_date);\n    $endTime = strtotime($dateofreg1);\n    $timeDiff = abs($startTime-$endTime);\n    $numberDays = $timeDiff/86400;\n    $numberDays = intval($numberDays);', 'http://www.mostlikers.com/2014/08/expiry-date-code-in-php.html'),
(49, 'First and Last Record in Mysql ', 'SELECT * FROM table_name ORDER BY column_id DESC;', 'http://www.mostlikers.com/2014/08/first-and-last-record-in-mysql.html'),
(50, 'Get current date and time in PHP', 'Get your current date and time in php, set your location default time zone get your current time zone.\nmanually set the timezone by using date_default_timezone_set before the date() or time().', 'http://www.mostlikers.com/2014/07/get-current-date-and-time-in-php.html'),
(51, 'PHP switch case Statement', 'Php value compare to multi value in the sense we use if else statement method that time we use lot of value comparison method  in if else statement method. 10 or 20 value comparison statement execute time take delay, that case use switch statement this multiple value check time and comparison method', 'http://www.mostlikers.com/2014/07/php-switch-case-statement.html'),
(52, 'PHP user defind function', 'PHP user defind function reduce program code. create your own function pass the parameters value to check the conditions. PHP gives you option to pass your parameters inside a function. You can pass as many as parameters.', 'http://www.mostlikers.com/2014/07/php-user-defind-function.html'),
(53, 'Find latitude and longitude with Google Maps', 'Google Maps is an application that allows users to find and search for locations. that Map to find the location based latitude and longitude coordinates. for any place Your search loction find on  latitude and longitude in google map.', 'http://www.mostlikers.com/2014/07/find-latitude-and-longitude-with-google.html'),
(54, 'SQL BETWEEN Operator', 'Sql Between operator find the database in between two database values. this operator used between and not between data filtering database', 'http://www.mostlikers.com/2014/07/sql-between-operator.html'),
(55, 'Rename file directory in php ', 'PHP rename() function changed old directory to new directory If new name exists, it will be overwritten. Sometime wrongly uploaded file images or folder that time use this function easy to rename the new directory or image name.', 'http://www.mostlikers.com/2014/07/rename-file-directory-in-php.html'),
(56, 'HTML input file accept Attribute', 'PHP rename() function changed old directory to new directory If new name exists, it will be overwritten. Sometime wrongly uploaded file images or folder that time use this function easy to rename the new directory or image name.', 'http://www.mostlikers.com/2014/07/html-input-accept-attribute.html'),
(57, 'Delete image from folder in php', 'Delete image from folder in php,Image Deleting From The Image Source Folder - PHP,How can I delete file from my uploads folder', 'http://www.mostlikers.com/2014/07/delete-image-from-folder-in-php.html'),
(58, 'Facebook style photo comment system', 'Facebook style photo gallery comment, facebook style comment system php,Facebook Style Wall Posting and Comments System,Facebook-like comment system using AJAX, PHP', 'http://www.mostlikers.com/2014/07/facebook-style-photo-comment-system.html'),
(59, 'How to Make a Simple Search Engine using PHP and MySQLi', 'How to Make a Simple Search Engine,How to Make a Simple Search Engine using PHP and MySQLi, search engine in php, google search box,search engin concept in php', 'http://www.mostlikers.com/2013/08/search-engine.html'),
(60, 'phpmyadmin sql query builder', 'phpmyadmin sql query builder,  How to generate a create table script for an existing', 'http://www.mostlikers.com/2014/05/phpmyadmin-sql-query-builder.html'),
(61, 'Facebook Style Drop Down Log out Menu', 'i have tried to facebook style drop down menu list. i used some few line simple jquery function. click down arrow drop down menu list display here i use div show and hide based on jquery code. i make some own css to designed the drop down menu.', 'http://www.mostlikers.com/2013/05/facebook-style-drop-down-log-out-menu.html'),
(62, 'Facebook style login system using Mysqli and CSS', 'Today i posted on facebook style login form using PHP and CSS 3. facebook login form username accept on 3 types email id, Phone number, facebook email id this are 3 ways to login to facebook if user can enter wrong password  search to the databasse to fetch the matching  username to display image in', 'http://www.mostlikers.com/2014/03/facebook-login.html'),
(63, 'PHP age calculator script', 'PHP age calculator script ,Find your age using PHP age calculator script. This code easy find your age and calculate total no.of days . try this simple coding make your own age calculator.', 'http://www.mostlikers.com/2014/03/php-age-calculator-script.html'),
(64, 'Multiple image upload concept using php & mysql', 'In this post i have explained How to upload multiple images in database. upload multiple images in php mysql, multiple image upload in php with database, multiple image upload in php code with databases,multiple file upload in php mysql database, upload multiple images in php mysql demo,how to uploa', 'http://www.mostlikers.com/2014/03/multiple-image-upload-concept-using-php.html'),
(65, 'PHP implode and explode concept', 'PHP implode and explode concept', 'http://www.mostlikers.com/2014/03/php-implode-and-explode-concept.html'),
(66, 'Simple Human verification code in php ', 'Simple Human verification code', 'http://www.mostlikers.com/2014/02/simple-human-verification-code-in-php.html'),
(67, 'PDO Form value inserting into Database ', 'Form for inserting using php and pdo', 'http://www.mostlikers.com/2014/02/pdo-inser-delete.html'),
(68, 'PDO tutorials ', 'mysqli to PDO connection, Pdo (Php data object)', 'http://www.mostlikers.com/2014/02/pdo-tutorials.html'),
(69, 'How to make a website in Photoshop', 'How to make a website in Photoshop, PSD to Html', 'http://www.mostlikers.com/2014/02/how-to-make-website-in-photoshop.html'),
(70, ' Find all your computer information', 'Find your all system information, dxdiag', 'http://www.mostlikers.com/2014/02/find-all-your-computer-information.html'),
(71, 'custom search engine', 'Google custom search engine', 'http://www.mostlikers.com/2014/02/custom-search-engine.html'),
(72, 'change the html 5 form validation defult error message', 'change the html 5 form validation defult error message, This post make on custom to change the HTML 5 Form validation error message. previously Error message Display on default so now you change custom message on input validation field.', 'http://www.mostlikers.com/2014/02/change-html5-msgs.html'),
(73, 'Dynamic menu with sub-menu using php and mysql', 'Dynamic menu with sub-menu using php and mysql', 'http://www.mostlikers.com/2014/02/php-menu-submenu.html'),
(74, 'PHP Email and mobile number validation script', 'In this post i have explain about how to validate the email address and mobile number in server side. Usually we use form validation scripts. It will work only client side,  But we need check the form values in server side.', 'http://www.mostlikers.com/2014/02/php-email-and-mobile-number-validation.html'),
(75, 'Newsletter subscription in php', 'Newsletter subscription in php, Subscribe to Newsletters,  Group mail', 'http://www.mostlikers.com/2013/09/News-lettet.html'),
(76, 'Gmail style chat user display online and offline concept ', 'Gmail chat, offline and online concept, Gmail style chat user display online and offline concept', 'http://www.mostlikers.com/2013/09/Gmail-chat.html'),
(77, 'Simple comments form using in php', 'Creating simple PHP contact form, Comments form in php, Creating a simple feedback form using PHP, How to Create a Contact Form, Simple PHP contact form Script', 'http://www.mostlikers.com/2013/08/comments-form.html'),
(78, 'How to create Dynamic Menu using php and mysqli', 'Dynamic menu, Mysqli,Css menu, How to make css menu in php, Admin panel menu,WordPress menu', 'http://www.mostlikers.com/2013/08/dynamic-menu.html'),
(79, 'Email subscription concept using php and mysqli ', 'Email subscription concept using php and mysqli , how to send email, News letter', 'http://www.mostlikers.com/2013/08/Email-subscription.html'),
(80, 'Random Number generator in php ', 'This coding using on mobile number verification codes , captcha , forget password, comments verification, its such as some authenticate to check user.', 'http://www.mostlikers.com/2013/08/random-number-generator-in-php.html'),
(81, 'Send Email concept using in php', 'Email send concept using in php, feedback form, form post value in email', 'http://www.mostlikers.com/2013/08/Email-concept-php.html'),
(82, 'Twitter style compose box', 'css style box, Twitter style box, compose box', 'http://www.mostlikers.com/2013/08/Twiter-input-box.html'),
(83, 'Mysqli using in php', 'Mysqli, How to connect database in mysqli, mysqli using in php, php in mysqli, Mysqli_real_escape,', 'http://www.mostlikers.com/2013/07/mysqli-php.html'),
(84, 'php simple login script', 'php simple login script, login script, how How to Create Login Page in PHP/MySQL, Create User Login in PHP', 'http://www.mostlikers.com/2013/07/Login-php.html'),
(85, 'pagination concept in php', 'This post concept based on pagination its simplify to view count the number of the database value make paging method simple to access first last database values . I make the company employee status using pagination concept just try and download this coding also include sql file', 'http://www.mostlikers.com/2013/07/pagination-concept-in-php.html'),
(86, 'Password reset concept in php', 'This concept based on login user reset forget password. Sometime use forget the login password  that time user send  request through  admin .the admin generate some authentication code send email on request user email id . The user can get the authentication code and again login to provide new passw', 'http://www.mostlikers.com/2013/07/password-reset-concept-in-php.html'),
(87, 'change password in php mysql code', 'Change password is an important feature in password protected website. Using this feature user have the option to change the current password to new password. In this post i have explain how to change the old password using php and mysqli.', 'http://www.mostlikers.com/2013/07/change-password-in-php-mysql-code.html'),
(88, 'Password Encryption function in php', 'This article is about how to password encrypt method . For an overview of cryptography technology encryption function password plain-text convert cipher-text this is use of hackers cannot read our given password. the password convert to md5 algorithm this usually needs a key-generation algorithm to ', 'http://www.mostlikers.com/2013/07/password-encryption.html'),
(89, 'Make simple page counter using php and mysql', 'A hit counter or a page counter counts the number of people that visit your page. If you have created a new website you might be interested how many people are visiting. so try this simple method count how many people visit on your website. this coding make MySQL update query using in php.', 'http://www.mostlikers.com/2013/07/page-count-php.html'),
(90, ' To check whether an email id exists or not in database using PHP', 'email check in php', 'http://www.mostlikers.com/2013/07/to-check-whether-email-id-exists-or-not.html'),
(91, 'Array / object using fetch query in php oops concept', 'Array / object using fetch query in php oops concept. \nObject Oriented Programming, or OPP  refers to the method of programming that invokes the use of classes to organize the data and structure of an application. object function code easy to fetch in database most of the programmer using oops princ', 'http://www.mostlikers.com/2013/07/array-object-using-fetch-query-in-php.html'),
(92, 'Post Database values one table to another table ', 'Post Database values one table to another table', 'http://www.mostlikers.com/2013/06/post-database-values-one-table-to.html'),
(93, 'Login and Signup tab using jquery', 'Login and Signup form tab using jquery', 'http://www.mostlikers.com/2013/06/login-and-signup-tab-using-jquery.html'),
(94, 'Image Zoom In and Zoom Out concept', 'Image Zoom In and Zoom Out concept', 'http://www.mostlikers.com/2013/06/image-zoom-in-and-zoom-out-concept.html'),
(95, 'Multiple Values selected of select box ', 'Multiple Values selected of select box', 'http://www.mostlikers.com/2013/06/multiple-values-selected-of-select-box.html'),
(96, 'search concept using html5', 'This post make on simple search concept making list on text box like Google search. store the values in option box <data list> tag this data list id  in search box. used to display a repeated list of items that are bound to the control.', 'http://www.mostlikers.com/2013/06/search-concept-using-html5.html'),
(97, 'Html5 form validation', 'HTML5 validations using attributes like pattern, required, autofocus on the input field type text, tel, email, search, password, datetime, color, range.', 'http://www.mostlikers.com/2013/06/html5-form-validation.html'),
(98, 'Typing animation text using Javascript', 'Typing animation text using Javascript', 'http://www.mostlikers.com/2013/06/News-Text.html'),
(99, 'select box disabled and pass the value concept', 'select box disabled and pass the value concept', 'http://www.mostlikers.com/2013/05/select-box-disabled-and-pass-value.html'),
(100, 'Html 5 Mobile number validation', 'Html5 Mobile number validation, html5 mobile number validation,mobile number validation in html5,10 digit mobile number validation in html5,html mobile number validation,pattern for mobile number validation in html5,pattern="[7-9]{1}[0-9]{9}"', 'http://www.mostlikers.com/2013/05/html-5-mobile-number-validation.html'),
(101, 'form action value move another form in php', 'form action value move another form in php', 'http://www.mostlikers.com/2013/05/form-action-value-move-another-form-in.html'),
(102, 'Css style Tab concept using Radio button', 'Css style Tab concept using Radio button', 'http://www.mostlikers.com/2013/05/css-style-tab-concept-using-radio-button.html'),
(103, 'Hidden username mobile number using sub string Method', 'Hidden username mobile number using sub string Method', 'http://www.mostlikers.com/2013/05/hidden-username-mobile-number-using-sub.html'),
(104, 'How to show web browser saved password ', 'This is one new step hack trick normally most of the user can saved the login password in our browser they will not remember about the saved password. This notes help to how to show our saved password on our browser.', 'http://www.mostlikers.com/2013/05/how-to-show-web-browser-saved-password.html'),
(105, 'Share links to social network sites with Yoursite', 'Share my Web page and url Directly link in Social media networks, social media  icons,', 'http://www.mostlikers.com/2013/05/share-your-web-page-and-url-directly.html'),
(106, 'javascript check retype password', 'Password Recheck script just call the values in get id to check the password matching or wrong. make this get password and retype password values simple method watch also have live demo', 'http://www.mostlikers.com/2013/05/recheck-password-using-javascript.html'),
(107, 'Style Login Light Box coding', 'Style Login Light Box coding', 'http://www.mostlikers.com/2013/05/style-login-light-box.html'),
(108, 'CSS style input box design coding', 'CSS style input box design coding,css text box design code\ntext box design in css examples\ncss text box style.This topic we discuss about CSS3 code. CSS3 they release lot of style code, here i am using text box design. CSS3 induced cursor focus script and hover change style also. Just follow this no', 'http://www.mostlikers.com/2013/04/css-input-box-design-style-coding.html'),
(109, 'website Popup Ads script', 'This Script have simply make to  Popup windows Ads through your website. just try this coding put on <head> tag after refresh page the pop windows automatically  open your website.', 'http://www.mostlikers.com/2013/04/website-popup-ads-script.html'),
(110, 'Download flash files from the website through an browser', 'Download flash files from the website through an browser', 'http://www.mostlikers.com/2013/04/download-flash-files-from-website.html'),
(111, 'Html 5 Validate in Text box', 'This required code use text box email, name , empty column, just give the name mention name="email"', 'http://www.mostlikers.com/2013/04/html-5-validate-in-text-box-coding.html'),
(112, 'Div Split coding ', 'This method Easy way Split Div basically Div split using only Grid but this coding simple method try this code.', 'http://www.mostlikers.com/2013/04/div-split-coding.html'),
(113, 'Show And Hide Concept in Radio Button ', 'Show hide concept based on similar div hide and show concept but choose the radio button div will be display function make on jquery. radio button value name call on div just choose radio button value increased div action show/ hide. jquery function called input names to changes the divs values.', 'http://www.mostlikers.com/2013/04/show-and-hide-concept-in-radio-button.html'),
(114, 'How to  hack windows 7 password', 'How to  hack windows 7 password, how,Hack Windows 7 / 8 Password Without Software,windows 7 password reset,windows 7 password hack cmd', 'http://www.mostlikers.com/2013/03/how-to-hack-windows-7-password.html'),
(115, 'Hover Change the image', 'This is make simple tricks about css concept based on multiple image choose on css just positions will be changed the image location most of the website designers use this method all small images to combine single image and use image positions. just try this below css code also have live demos', 'http://www.mostlikers.com/2013/01/onclick-change-photo.html'),
(116, 'On-click Select Box Link using Javascript', 'On-click Select Box Link using Javascript give link location..', 'http://www.mostlikers.com/2013/01/select-box-link-without-ajax-javascript.html'),
(117, 'Select All Check box java Script', 'Select All Check box java Script', 'http://www.mostlikers.com/2013/01/select-all-check-box-in-javascript.html'),
(118, 'Add multiple email accounts to your Gmail account using SMTP Configuration', 'how to configure your multiple emails accounts to google gmail account, Gmail account has more features, here im going to tell you the one, which is more useful to everyone. here im going to configure how to add multiple email id in single email account. if your adding like this, you can send email ', 'http://www.2my4edge.com/2016/02/add-multiple-email-accounts-to-your_3.html'),
(119, 'Create ZIP format and download whole folder or file using php', 'create or make zip file using php, by using php we can make .zip format, here we are going make whole folder or particular file as in zip format. let me show the php code.', 'http://www.2my4edge.com/2016/01/create-zip-format-whole-folder-or-file.html'),
(120, 'When we click on mobile number on webpage, Call through skype or show in mobile dialer screen to cal', 'Usually in webpage we are displaying mobile number for contact us, When we are giving that number we are just simply giving only number, her ei have solution for that, When we are clicking on that number it will show mobile dialer screen to dial directly in mobile or if you want to call in skype, yo', 'http://www.2my4edge.com/2015/12/when-click-on-mobile-number-on-webpage.html'),
(121, 'Complete basic insert, view, edit, delete and update in Codeigniter', 'Codeigniter is one of the popular framework in php, here we are going to learn about complete basic functionality of codeignter like insert, view, edit, delete and update. This will help all the codeignter workers. with this functionality they manage codeignter and easy learn the functionality. Let ', 'http://www.2my4edge.com/2015/12/complete-basic-insert-view-edit-delete.html'),
(122, 'Show menu bar in scroll up, hide in scroll down using Javascript with Bootstrap', 'Now a days most of the sites are using this kind of nav bar,  like when we are scrolling down hiding the menu nav bar, When we are scrolling up showing the menu nav bar, actually it is really nice one. here we are going to create like that kind of functionality only using jquery javascript and with ', 'http://www.2my4edge.com/2015/12/show-menu-bar-in-scroll-up-hide-in.html'),
(123, 'Save the particular div in PDF format onclick using Jquery', 'Save or download the particular div as in the PDF format onclick using jsPDF jquery file. This is very simple one. i already showed you one tutorial to save and print the whole web page. here for the particular div. let see the code. using jquery', 'http://www.2my4edge.com/2015/11/save-particular-div-in-pdf-format.html'),
(124, 'Unlimited repeating data loading scroll using Jquery', 'loading unlimited data while scrolling down to the page. im going to use iscroll.js to make this kind of function. most of the site are using this kind of script to make the data lengthy. this make help to stay people in the page. like that in the load-data.html also we are loading the same page ins', 'http://www.2my4edge.com/2015/11/unlimited-repeating-data-loading-scroll.html'),
(125, 'Auto complete Google map in form input type using geocomplete Jquery', 'interesting thing regarding web development. now a days most of the website need google map location while we are entering location name, for that we have one solution. When we are entering the location name in input type you will get map for that particular location by using Jquery', 'http://www.2my4edge.com/2015/10/auto-complete-google-map-in-form-input.html'),
(126, 'Multiple image upload preview before image uploading to the server using Jquery', 'useful tip for multiple image uploading preview, when ever we are uploading image we need instant image preview, for that we are going to use html5 filereader. and here we are going to use the jquery for instant image preview. let see the simple code.', 'http://www.2my4edge.com/2015/10/multiple-image-upload-preview-before.html'),
(127, 'Usage of Animate.css. One of the finest CSS library for animations', 'This is one the finest CSS library file to make you web page with attractive animated designs. it is cross browser library css file. it very easy to use in web page. it contains more Effects. We can use this library in our project make the page very neat and attractive. let see the details about the', 'http://www.2my4edge.com/2015/07/usage-of-animatecss-one-of-finest-css.html'),
(128, 'Remove repeated entries in select option dropdown using Javascript', 'Avoid duplicate entries in selection option dropdown using javascript, this is mostly used in php, while fetching multiple data in dropdown select, that time we need to avoid duplicate entries, that time we need this script, or else we have to use group by query, here we are using that without mysql', 'http://www.2my4edge.com/2015/06/remove-repeated-entries-in-select.html'),
(129, 'Very flexible Hover css effects using Hover.css', 'I was used this css to my recent project, This is really nice and time consumes for css hover effects. Here it is very simple we just have to give to class name in the class and it will automatically takes that realted effect. this is very simple for hover effects. let me tell the details about the ', 'http://www.2my4edge.com/2015/05/very-flexible-hover-css-effects-using.html'),
(130, 'Simple textarea text counter using bootstrap', 'Twitter style textarea character counter using Bootstrap and javascript, here is the one of the simple method use the textarea counter, this is very useful to limited character field in forms. after a long time this post is about bootstrap. It is very simple one. text counter with validation until y', 'http://www.2my4edge.com/2015/05/simple-textarea-text-counter-using.html'),
(131, 'Allow html tags and files only to particular page URL using php', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/04/allow-html-tags-and-files-only-to-particular-url.html'),
(132, 'Simple blinking effect using css3 and Jquery', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/04/simple-blinking-effect-using-css3-and.html'),
(133, 'Connect website through LAN without internet using WAMP server ', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/03/connect-website-through-lan-without.html'),
(134, 'Responsive back to top using Bootstrap', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/03/responsive-back-to-top-using-bootstrap.html'),
(135, 'Animated background Color changer using Jquery UI', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/03/animated-background-color-changer-using.html'),
(136, 'Google Doodles style animation using Jquery', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/google-doodles-style-animation-using.html'),
(137, 'Set custom username url for your facebook account', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/set-custom-username-url-for-your.html'),
(138, 'Peeling style on top corner of browser using peelback jquery ', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/peeling-style-on-top-corner-of-browser.html'),
(139, 'Get Google alerts to your mail ', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/get-google-alerts-to-your-mail.html'),
(140, 'Confirmation alert on before closing browser tab using Javascript ', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/confirmation-alert-on-before-closing.html'),
(141, 'Responsive navbar menu using bootstrap', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/responsive-navbar-menu-using-bootstrap.html'),
(142, 'Connect Whats app to computer through Android phone ', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/connect-whats-app-to-computer-through.html'),
(143, 'How to add custom google search engine to our websites', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/how-to-add-custom-google-search-engine.html'),
(144, 'How to add Google translator to our website', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/how-to-add-google-translator-to-our.html'),
(145, 'Live HTML Compiler using PHP like W3schools tryit editor', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/02/live-html-compiler-using-php-like.html'),
(146, 'How to create a form in Google Drive for Request and Response', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/01/how-to-create-form-in-google-drive-for.html'),
(147, 'Simple updated dynamic datatable using Bootstrap (NEW)', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/01/simple-updated-dynamic-datatable-using.html');
INSERT INTO `web_information` (`id`, `meta_title`, `meta_description`, `site_url`) VALUES
(148, 'Responsive Full screen slider using Bootstrap', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2015/01/responsive-full-screen-slider-using.html'),
(149, 'Simple voting concept based on ip address using php with Ajax', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2014/12/simple-voting-concept-based-on-ip.html'),
(150, 'Simple Responsive Quote style Carousel Slider', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2014/12/simple-responsive-quote-style-carousel.html'),
(151, 'Simple dropdown menu with Bootstrap', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2014/12/simple-dropdown-menu-with-bootstrap.html'),
(152, 'Step by step tab style form validation Wizard using Bootstrap', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2014/12/step-by-step-tab-style-form-validation.html'),
(153, 'Subscribe pop up alert box on scroll down and onload using subscribe better js', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2014/12/subscribe-pop-up-alert-box-on-scroll.html'),
(154, 'Fetch two different table data in single page using PHP and MySql', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2014/12/fetch-two-different-table-data-in.html'),
(155, 'Basic insert, view, edit, delete and update using PHP and Mysql', 'We are mostly using header and footer as separate page. so that time when we are adding one in header or footer file it will affect all the files that, so for we have to take that files only to the particular url, then only it will works well. we can add css, javascript and jquery to particular page', 'http://www.2my4edge.com/2014/12/basic-insert-view-edit-delete-and.html'),
(156, 'PHP Email template for contact user and admin', 'Template based Email sending,HTML Email template in PHP,PHP Mailer with HTML template and sending variables,Send email with a template using php,Free Email Templates for HTML Newsletter Campaign', 'http://www.2my4edge.com/2014/11/php-email-template-for-contact-user-and.html'),
(157, 'Dynamic data binding using angularjs', 'Dynamic data binding in angularjs,data binding in angularjs example,How to display Database data using Angular JS', 'http://www.2my4edge.com/2014/11/dynamic-data-binding-using-angularjs.html'),
(158, 'Gird and List style view onclick by using Jquery', 'how to do the grid/list style view mode onclick by using javascript and jquery. this is very simple one. but in this post you have to concentrate on girds in css. but here i done only one gird for my sample. making grid to list and list to gird by clicking the icon.', 'http://www.2my4edge.com/2014/07/gird-and-list-style-view-onclick-by.html'),
(159, 'Set current time using javascript for websites', 'Set current time using javascritpt, most of the websites need time to display time in their website, for that, here we are going to set simple javascript digital timer in our website. it is one of the simple one. let see the coding.', 'http://www.2my4edge.com/2014/07/set-current-time-using-javascript-for.html'),
(160, 'Portfolio Design and sorting with Animation Effect', 'how to make simple and attractive portfolio design and sorting with Animation effects. In this post, we are going to use Jquery and CSS to make this function. this is one of the simple way. let see the coding with details.', 'http://www.2my4edge.com/2014/06/portfolio-design-and-sorting-with.html'),
(161, 'Send an Email by using PHPmailer ', 'how to send a Email using phpmailer, it is a simple one. here we have class.phpmailer.php file, that make send mail operation very simple and calm. here we just have to do some simple steps to do this method. check this by the live demo. this phpmailer class file makes to attach a file with a mail. ', 'http://www.2my4edge.com/2014/05/send-email-by-using-phpmailer.html'),
(162, 'Onload Fancy box Using Jquery', 'Onload Fancy box using Jquery, yes it may harmful to web page. it is like a popup box. popup box is one of the most irritating thing in web designing and web development, but most of them need this script for their own, personal and e-commerce site. jquery, popup window, onload,', 'http://www.2my4edge.com/2014/01/onload-fancy-box-using-jquery.html'),
(163, 'Accordion toggle using Jquery with Bootstrap', 'Accordion toggle is new style of toggle, this accordion is mostly using for FAQ and design features, so this kind of toggle is make the web page as very attractive, and here we are going to use this with Bootstrap plugin. let see the coding.', 'http://www.2my4edge.com/2013/12/accordion-toggle-using-jquery-with.html'),
(164, 'Go back to previous and next page onClick in browser using Javascript', 'Sometimes this script may very useful to every web designers, go back to previous or next page in browser using javascript. here we are going to see how make, go back to previous and next page onclick in browser using javascript. let see the simple code.', 'http://www.2my4edge.com/2013/11/go-back-to-previous-and-next-page.html'),
(165, 'Dynamic Data Table using DataTable Jquery', 'Dynamic Data table using dataTable Query is very simple and useful plugin technique, here we are going to see about that DataTable functions and features. this Dynamic data table has more feature within it, such as Search, Sorting, Pagination, field count, views per page. Those all features contains', 'http://www.2my4edge.com/2013/11/dynamic-data-table-using-datatable.html'),
(166, 'Image zoom on hover using css3', 'Image zoom on hover using css3, this is actually very simple and useful tip to all web designers. here we have already discussed more tutorials about designing and here one more thing. it may useful to make portfolio and other designing purpose. let see the details about that.', 'http://www.2my4edge.com/2013/10/image-zoom-on-hover-using-css3.html'),
(167, 'Resize the font using Query', 'Resize the font size using JQuery is very simple one, Onclick how to make font size increase and decrease using Jquery. here we are going to see thing about designing. just make simple thing, it is also like magnifying the text onclick. usually we are using shortcut key CTRL + + or CTRL + - to zoom ', 'http://www.2my4edge.com/2013/08/resize-font-using-query.html'),
(168, 'Get support with foreign and regional language in php and mysql', 'Usually you may know  or donâ€™t know, in a PhpMyadmin default setting does not support the foreign and regional language. It default supporting language is English. Iâ€™m from India, so here most of them using so many languages. So today Iâ€™m going to show you that how to insert the foreign and re', 'http://www.2my4edge.com/2013/08/get-support-with-foreign-and-regional.html'),
(169, 'Ajax delete with PHP and MySql', 'Ajax delete with confirm box, here we are going to see about how to delete the data without refreshing page and with confirmation box, and this is what most of them searching, so today going to show you that, how to make this alert style box delete with ajax and php, mysql.', 'http://www.2my4edge.com/2013/08/ajax-delete-with-php-and-mysql.html'),
(170, 'How to create an animated .jpg image', 'Here Iâ€™m going to show you that, how to make animated image with the extension of .jpg. we all know that, the .jpg file (joint photography experts group) does not support animation and all. But here we have some tricks to make it.', 'http://www.2my4edge.com/2013/08/how-to-create-animated-jpg-image.html'),
(171, 'Animated scroll to top by using Jquery', 'Animated Scroll to top by using JQuery is one the simple technique, here we going to see that. how i made this with simple coding. this back to top or scroll to top is mostly used for the purpose of going down to the page by scrolling. and have go back to the top of the page. so for we are using thi', 'http://www.2my4edge.com/2013/08/animated-scroll-to-top-by-using-jquery.html'),
(172, 'Rotate image on hover using CSS3', 'Rotate image on image hover using CSS3. now in CSS3 in most flexible to make more animations and more design by using CSS coding. similarly here we are going to see how to make animated rotating image on image hover by using CSS transform code. by using this transform we can rotate the image. and al', 'http://www.2my4edge.com/2013/08/rotate-image-on-hover-using-css3.html'),
(173, 'Autocomplete search using php, mysql and ajax', 'We know what is autocomplete in input type, that is make some predefined entered texts come under the input type box, while focusing on the input type, similarly we are searching some content from mysql database, this actually facebook style search concept to suggest some data for select before we g', 'http://www.2my4edge.com/2013/08/autocomplete-search-using-php-mysql-and.html'),
(174, 'Enable right click in right click disabled web pages by disable javascript in browser', 'Most of the site are disabled the right click button for the security purpose. But what we do is try to hack this site, as I said in the previous tutorial right click disabled is not much secured, so we have to use some tricks to enable right click in the right click disable pages. So let see.  This', 'http://www.2my4edge.com/2013/07/enable-right-click-in-right-click.html'),
(175, 'Disable right click and protect your content from coping using Java script', 'Disable right click button in mouse using javascript, this concept is mostly used for protect your content from coping your copy right content and all, most of the hacker trying to copy your content and try to reveal your secret of your web page, thatâ€™s why this script is using for protect. If we ', 'http://www.2my4edge.com/2013/07/disable-right-click-and-protect-your.html'),
(176, 'Most popular posts in 2my4edge', 'most popular post in 2my4edge.com, and all kind of tutorials and demos with examples what i done in 2my4edge. focused on php, javascript, mysql, html, css, css3, html5, jquery, plugins, .htaccess, style, design. and more.', 'http://www.2my4edge.com/2013/07/most-popular-posts-in-2my4edge.html'),
(177, 'Export the MySQL database table as CSV format using PHP', 'Export the database as in the format of CSV to open it in the Microsft office (MS)-Excel. Most the social media sites and E-commerce site and more sites or this kind of database export coding for without going to admin panel, just in one click export the database table as in the format of CSV to ope', 'http://www.2my4edge.com/2013/07/export-mysql-database-table-as-csv.html'),
(178, 'Create custom file chosen input type using Css and Jquery', 'Usually we know how to give input type file for upload any kind of file in the database, for that we are using form, and in that form we have to give input type="file" for file upload, usually while we are calling the input type as like the above, that will change for each browser, for that and make', 'http://www.2my4edge.com/2013/07/create-custom-file-chosen-input-type.html'),
(179, 'Change text & background color while selecting text using CSS3', 'Change text color and background color while you are selecting text for copy or any other purpose, make your web page impressive with extra design using this css selection text color change, getting bored of usual selecting color on your web page, so try this code. While selecting content of any web', 'http://www.2my4edge.com/2013/07/change-text-background-color-while.html'),
(180, 'Marquee style in different manner with PHP and MySql', 'Marquee style scroll using in different manner, such as top to bottom, bottom to top, left to right, right to left, and scroll speed control, like all those details we are going to discuss here. usually all web developer must this tag that is marquee tag, which this marquee tag is used for the purpo', 'http://www.2my4edge.com/2013/07/marquee-tag-style-in-different-manner.html'),
(181, 'My Demos page design details with all my tutorials', 'php, html, ajax, javascript, jquery, all web development process, web solution. my blogging expreiance, initial stage of my blog, demo pages, every thing comes here under the page demo, check all your needs.', 'http://www.2my4edge.com/2013/07/my-demos-page-design-details-and-all-my.html'),
(182, 'Simple Login logout system using php', 'Login and logout system is the most important thing for the user management, session management is one important thing for manage the user for the whole time of login time. for that we have to use session for this. it should have 5 files for this. we have to fetch the same value for the user and che', 'http://www.2my4edge.com/2013/07/simple-login-logout-system-using-php.html'),
(183, 'Username live availability Check using php and Ajax', 'Username live availability is one of the most important thing the database field, why because mostly we have to different kind of username and unique name for all users. then only we can identify the individual user, so for here we are going to check the database field for already existing username ', 'http://www.2my4edge.com/2013/07/username-live-availability-check-using.html'),
(184, 'How to create custom 404 error page using .htaccess', 'Most of the web pages show the error like 404 page error.  So here we have solution to make the custom web page for that 404 page error by using .HTACCESS.  This 404 error make your website uneasy. So here we are using the HTACCESS file for that. As we know already we discussed here about how to mak', 'http://www.2my4edge.com/2013/07/how-to-create-custom-404-error-page.html'),
(185, 'Image Zoommer like E-commerce site using multizoom.js', 'Usually we need this kind of image zoom is using in E-commerce site, Why because, they want to show their product with some extra quality, thatâ€™s why they are using this image zoom on their product, here we are going to see how the image zoom get works.', 'http://www.2my4edge.com/2013/07/image-zoommer-like-e-commerce-site.html'),
(186, 'Facebook style Scroll bar using Jquery', 'Most of them eager to know about facebook and itâ€™s functionality, so here we just know about facebook style scroll bar, how the scroll bar is seems in the facebook, the black color scroll bar and it presence when we hover the part where the scroll is presence, similar like the same style the scrol', 'http://www.2my4edge.com/2013/06/facebook-style-scroll-bar-using-jquery.html'),
(187, 'Change background image while page refresh using Javascript', 'Are you getting bore of the same background image on your web page, no worries. For each refresh/reload of your web page, change new and new background images using javascript. It is very simple concept by using javascript. This page background change is make is your web page more impressive and not', 'http://www.2my4edge.com/2013/06/change-background-image-while-page.html'),
(188, 'Browser full screen API using Query', 'Full screen mode of browser, usually for this full screen mode we just press button f11 key, here we are going to see that in coding using fullscreen Jquery. By the help of this coding when we press the location the browser will be as full screen mode, in most of the social media network sites using', 'http://www.2my4edge.com/2013/06/browser-full-screen-api-using-query.html'),
(189, 'Facebook Style Textarea Auto Grow Using JQuery Plugin and Css', 'Usually textarea is one of the form input type, it is identified by rows and cols, while using Rows and Cols the textarea will be comes like scrolled type for that we are going to disable the scroll bar and grow the textarea.\n\nFor that we are using Textarea autogrow plugin to expand the textarea and', 'http://www.2my4edge.com/2013/06/facebook-style-textarea-auto-grow-using.html'),
(190, 'Print or Save the Web page as .PDF  Using Java Script', 'Save the web page as .PDF format or directly print the page using printer, we have to connect the printer through the computer and then choose the Designation where and what it should have to do the function, whether print or save the page.', 'http://www.2my4edge.com/2013/06/print-or-save-web-page-as-pdf-using.html'),
(191, '.htaccess uses and redirect www to non-www and non-www to www', 'Initially I donâ€™t the purpose of .htaccess and now I bought my own domain so, I realized the need of .htaccess, here I just use this .htaccess for redirect website URL www to non-www and non-www to www. Let see how the .htaccess code is works here, and how we want to use this .htaccess.', 'http://www.2my4edge.com/2013/06/htaccess-uses-and-redirect-www-to-non.html'),
(192, 'Choose state and city based on country using Jquery', 'Itâ€™s  for choosing state and city based on choosing the country, when we choose a country, in a second select option field will show the states, what are all presents in the country, that is the concept. Let see how it works', 'http://www.2my4edge.com/2013/06/choose-state-and-city-based-on-country.html'),
(193, 'Change the colored image into black and white image on image hover', 'Here we go, changing of colored image into black and white image on image hover. So here we are going to apply the gray-scale property, when the grayscale is on 100% the image will become intoblack and white image. gray-scale', 'http://www.2my4edge.com/2013/06/change-colored-image-into-black-and.html'),
(194, 'Comment System using PHP and MySql', 'Here we are going to see about comment system suing PHP and MySql, here it is useful to all webpage feedback system like user comments Displays at the end of all WebPages thatâ€™s what we are going to see here', 'http://www.2my4edge.com/2013/05/comment-system-using-php-and-mysql.html'),
(195, 'Simple concept for Select All text OnClick in textarea', 'generating any kind of code, that will shown in textarea, after that we just click on that textarea that will select all the texts in the textarea, how it works', 'http://www.2my4edge.com/2013/05/simple-concept-for-select-all-text.html'),
(196, 'Create Database with MySql and INSERT coding in php', 'It is basics of PHP, here we are going to see about How to crate database and how insert the field values in the database table.', 'http://www.2my4edge.com/2013/05/create-database-with-mysql-and-insert.html'),
(197, 'Create facebook app and invite or bring your friends to site', 'invite facebook friends and bring friends using that facebook application we can bring your facebook friends to your site, for that we have create a facebook app and have to proceed some steps, let see what it is.', 'http://www.2my4edge.com/2013/05/create-facebook-app-and-invite-or-bring.html'),
(198, 'Floating menu using Jquery plugin', 'floating div or floating menu concept is usually used for the purpose of fixed or absolute positions of ads or some other important thing, so that we are using this floating menu concept, let see how it works with Jquery plugin', 'http://www.2my4edge.com/2013/05/floating-menu-using-jquery-plugin.html');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `web_information`
--
ALTER TABLE `web_information`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `web_information`
--
ALTER TABLE `web_information`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=199;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
